version: '3.5'  
services:  
  web:
    build: .
    container_name: hiface_api_container
    volumes:
      - ./src:/src
    ports:
      - "8123:8000"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: unless-stopped